name: segunda-oportunidad
on:
  push: 
    branches: [ "main" ]

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
      - name: pruebaaa
        run: echo 'hola que hace'
      - name: obtener secreto
        run: echo ${{secrets.secreto_prueba}}
